using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class OVRHandTrackingConfidenceModel
{
    // 0 = low confidence, 1 = high confidence
    [RealtimeProperty(1, false, true)] private int _handTrackingConfidence;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class OVRHandTrackingConfidenceModel : RealtimeModel {
    public int handTrackingConfidence {
        get {
            return _handTrackingConfidenceProperty.value;
        }
        set {
            if (_handTrackingConfidenceProperty.value == value) return;
            _handTrackingConfidenceProperty.value = value;
            InvalidateUnreliableLength();
            FireHandTrackingConfidenceDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(OVRHandTrackingConfidenceModel model, T value);
    public event PropertyChangedHandler<int> handTrackingConfidenceDidChange;
    
    public enum PropertyID : uint {
        HandTrackingConfidence = 1,
    }
    
    #region Properties
    
    private UnreliableProperty<int> _handTrackingConfidenceProperty;
    
    #endregion
    
    public OVRHandTrackingConfidenceModel() : base(null) {
        _handTrackingConfidenceProperty = new UnreliableProperty<int>(1, _handTrackingConfidence);
    }
    
    private void FireHandTrackingConfidenceDidChange(int value) {
        try {
            handTrackingConfidenceDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _handTrackingConfidenceProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _handTrackingConfidenceProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.HandTrackingConfidence: {
                    changed = _handTrackingConfidenceProperty.Read(stream, context);
                    if (changed) FireHandTrackingConfidenceDidChange(handTrackingConfidence);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _handTrackingConfidence = handTrackingConfidence;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
